### ISSUE TITLE
A markdown test

### ISSUE THREAD

**Issue by uraincay** [uraincay/gittest#2]
#1.Task list markdown
-[x] write the code
-[  ] write all the tests
-[  ] Document the code
- [X] Write the code
   - [ ] Write all the tests
   - [ ] Document the code
